### ISSUE TITLE
Block reward: first block with 70+ AEON coins?

### ISSUE THREAD

**Issue by ghost** [thriftyMinnow/aeon-whitepaper#2]
From the PDF:

> Thus, the very first block reward on June 6, 2014 calculated to just over 70 AEON coins. Since the
current supply of coins (A) increases with every new block, each successive reward will decrease by
a small fraction of a coin.

However, when searching for the information in the [block explorer](https://aeonblocks.com/search?value=1), the first block had, in fact, a number of outputs similar to that of Monero. It is normal that at the birth of the network the blocks came out with a difference of mere seconds, but still, the first block had a value of approximately 17 AEON.

Even if you considered the reward among all mined blocks within the first 4 minutes (average time between blocks) that would give a larger value, of approximately 228 AEON.

The value in document (70) is based solely on the formula? If so, it might be worth clarifying this point, since anyone who checks the blockchain can see that the value is different.

**Comment by thriftyMinnow** [comment]
Nice catch!  I also had realized this and looked into it.  AEON started with the same 1 minute block times as Monero, and later modified to the current 4 minutes.  I have removed the incorrect text from the paper, and included the information on the hard fork modification.
